name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
        - '2.6.10'
        - '2.7.8'
        - '3.0.7'
        - '3.1.5'
        - '3.2.4'
        - '3.3.1'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bin/rspec

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1
        bundler-cache: true

    - name: Run Rubocop
      run: bin/rubocop
